const eventTypes = {
  CREATE_EVENT: "CREATE_EVENT",
  FETCH_EVENTS: "FETCH_EVENTS",
  DELETE_EVENT: "DELETE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  FETCH_EVENT_BY_ID: "FETCH_EVENT_BY_ID",
  ATTENDING_CHECK: "ATTENDING_CHECK",
  LOADING: "LOADING"
};

export default eventTypes;